apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nereid-tests.fullname" . }}-prod-configmap
data:
  CELERY_BROKER_URL: "redis://{{ .Values.global.domains.nereidRedis }}/0"
  CELERY_RESULT_BACKEND: "redis://{{ .Values.global.domains.nereidRedis }}/0"
  NEREID_ASYNC_MODE: "replace"