apiVersion: v1
kind: Secret
metadata:
  name: nereid-tests-volume-secret
type: Opaque
data:
  azurestorageaccountname: {{ .Values.global.secrets.applicationStorageAccountName | b64enc }}
  azurestorageaccountkey: {{ .Values.global.secrets.applicationStorageAccountKey | b64enc }}