delete from dbo.FieldDefinition
go

INSERT [dbo].[FieldDefinition] ([FieldDefinitionID], [FieldDefinitionName], [FieldDefinitionDisplayName], [DefaultDefinition], CanCustomizeLabel) 
VALUES 
(1, N'IsPrimaryContactOrganization', N'Is Primary Contact Organization', N'<p>The entity with primary responsibility for organizing, planning, and executing implementation activities for a project or program. This is usually the lead implementer.</p>', 1),
(2, N'Organization', N'Organization', N'<p>A partner entity that is directly involved with implementation or funding a project.&nbsp;</p>', 1),
(3, N'Password', N'Password', N'<p>Password required to log into the ProjectNeptune tool in order to access and edit project and program information.</p>', 0),
(4, N'MeasurementUnit', N'Measurement Unit', N'<p>The unit of measure used by an Indicator (aka&nbsp;Performance Measure) to track the extent of implementation.</p>', 1),
(5, N'PhotoCaption', N'Photo Caption', N'<p>A concise yet descriptive explanation of an uploaded photo. Photo captions are displayed in the lower right-hand corner of the image as it appears on the webpage.</p>', 1),
(6, N'PhotoCredit', N'Photo Credit', N'<p>If needed, credit is given to the photographer or owner of an image on the website. Photo credits are displayed in the lower right-hand corner of the image as it appears on the webpage.</p>', 1),
(7, N'PhotoTiming', N'Photo Timing', N'<p>The phase in a project timeline during which the photograph was taken. Photo timing can be before, during or after project implementation.&nbsp;</p>', 1),
(8, N'PrimaryContact', N'Primary Contact', N'<p>An individual at the listed organization responsible for reporting accomplishments and expenditures achieved by the project or program, and who should be contacted when there are questions related to any project associated to the organization.</p>', 1),
(9, N'OrganizationType', N'Organization Type', N'<p>A categorization of an organization, e.g. Local, State, Federal or Private.</p>', 1),
(10, N'Username', N'User name', N'<p>Password required to log into the system&nbsp;order to access and edit project and program information that is not allowed by public users.</p>', 1),
(11, N'ExternalLinks', N'External Links', N'<p>Links to external web pages where you might find additional information.</p>', 1),
(12, N'RoleName', N'Role Name', N'<p>The name or title describing&nbsp;function or set of permissions that can be assigned to a user.</p>', 1),
(13, N'Chart Last Updated Date', 'ChartLastUpdatedDate','<p>The date this chart was last updated with current information.</p>', 1),
(14, N'TreatmentBMPType', N'Treatment BMP Type', '', 1),
(16, N'ConveyanceFunctionsAsIntended', N'Conveyance Functions as Intended', '', 1),
(17, N'AssessmentScoreWeight', N'Assessment Score Weight', '', 1),
(18, N'ObservationScore', N'Observation Score', '', 1),
(19, N'AlternativeScore', N'Alternative Score', '', 1),
(20, N'AssessmentForInternalUseOnly', N'Assessment for Internal Use Only', '', 1),
(21, N'TreatmentBMPDesignDepth', N'Treatment BMP Design Depth', '', 1),
(22, N'ReceivesSystemCommunications', N'Receives System Communications', '', 1),
(23, N'Jurisdiction', N'Jurisdiction', '', 1),
(24, N'ModeledCatchment', N'Modeled Catchment', '', 1),
(25, N'TreatmentBMP', N'Treatment BMP', '', 1),
(26, N'TreatmentBMPAssessmentObservationType', N'Observation Name', '', 1),
(27, N'ObservationCollectionMethod', N'Collection Method', '', 1),
(28, N'ObservationThresholdType', N'Threshold Type', '', 1),
(29, N'ObservationTargetType', N'Target Type', '', 1),
(30, N'MeasurementUnitLabel', N'Measurement Unit Label', '', 1),
(31, N'PropertiesToObserve', N'Properties To Observe', '', 1),
(32, N'MinimumNumberOfObservations', N'Minimum Number of Observations', '', 1),
(33, N'MaximumNumberOfObservations', N'Maximum Number of Observations', '', 1),
(34, N'MinimumValueOfEachObservation', N'Minimum Value of Each Observation', '', 1),
(35, N'MaximumValueOfEachObservation', N'Maximum Value of Each Observation', '', 1),
(36, N'DefaultThresholdValue', N'Default Threshold Value', '', 1),
(37, N'DefaultBenchmarkValue', N'Default Benchmark Value', '', 1),
(38, N'AssessmentFailsIfObservationFails', N'Assessment Fails if Observation Fails', '', 1),
(39, N'CustomAttributeType', N'Attribute Name', '', 1),
(40, N'CustomAttributeDataType', N'Data Type', '', 1),
(41, N'MaintenanceRecordType', N'Maintenance Type', 'Whether the maintenance performed was Preventative or Corrective maintenance', 1),
(42, N'MaintenanceRecord', N'Maintenance Record', 'A record of a maintenance activity performed on a Treatment BMP', 1),
(43, N'AttributeTypePurpose', N'Purpose', 'How the attribute type will be used for analysis and reporting', 1),
(44, N'FundingSource', N'Funding Source', '', 1),
(45, N'IsPostMaintenanceAssessment', N'Post Maintenance Assessment?', 'Whether the assessment was conducted as a follow-up to a maintenance activity', 1),
(46, N'FundingEvent', N'Funding Event', 'A discrete activity (e.g. Project planning, major maintenance, capital construction) that invests in a BMP. A funding event consists of one or funding sources and associated expenditures', 1),
(47, N'FieldVisit', N'Field Visit', 'A visit to a Treatment BMP which can consist of an Assessment, a Maintenance Record, and a Post-Maintenance Assessment', 1),
(48, N'FieldVisitStatus', N'Field Visit Status', 'Completion status of the Field Visit. A Field Visit can be In Progress, Complete, or left Unresolved. A Treatment BMP may only have one In Progress Field Visit at any given time.', 1),
(49, N'WaterQualityManagementPlan', N'Water Quality Management Plan', N'', 1),
(50, N'Parcel', N'Parcel', N'', 1),
(51, N'RequiredLifespanOfInstallation', N'Required Lifespan of Installation', N'Specifies when or whether a BMP can be removed', 1),
(52, N'RequiredFieldVisitsPerYear', N'Required Field Visits Per Year', N'Number of Field Visists that must be conducted for a given BMP each year', 1),
(53, N'RequiredPostStormFieldVisitsPerYear', N'Required Post-Storm Field Visits Per Year', N'Number of Post-Storm Field Visists that must be conducted for a given BMP each year', 1),
(54, N'WaterQualityManagementPlanDocumentType', N'WQMP Document Type', N'Specifies what type of supporting document this is. Some document types are required for a WQMP to be considered complete', 1),
(55, N'HasAllRequiredDocuments', N'Has All Required Documents?', N'Indicates whether all required supporting documents are present for a WQMP', 1),
(56, N'DateOfLastInventoryChange', N'Date of Last Inventory Change', '', 1)