Create Table dbo.TreatmentBMPAttributeTypePurpose(
TreatmentBMPAttributeTypePurposeID int not null constraint PK_TreatmentBMPAttributeTypePurpose_TreatmentBMPAttributeTypePurposeID primary key,
TreatmentBMPAttributeTypePurposeName varchar(60) not null constraint AK_TreatmentBMPAttributeTypePurpose_TreatmentBMPAttributeTypePurposeName unique,
TreatmentBMPAttributeTypePurposeDisplayName varchar(60) not null constraint AK_TreatmentBMPAttributeTypePurpose_TreatmentBMPAttributeTypePurposeDisplayName unique,
)
GO
-- for emphasis
GO
GO

Alter Table dbo.TreatmentBMPAttributeType
Add TreatmentBMPAttributeTypePurposeID int null constraint FK_TreatmentBMPAttributeType_TreatmentBMPAttributeTypePurpose_TreatmentBMPAttributeTypePurposeID foreign key references dbo.TreatmentBMPAttributeTypePurpose(TreatmentBMPAttributeTypePurposeID)
GO

Insert Into dbo.TreatmentBMPAttributeTypePurpose(TreatmentBMPAttributeTypePurposeID, TreatmentBMPAttributeTypePurposeName, TreatmentBMPAttributeTypePurposeDisplayName)
values
(1, 'DesignParameter', 'Design Parameter'),
(2, 'Other', 'Other')

Update dbo.TreatmentBMPAttributeType
set TreatmentBMPAttributeTypePurposeID = 1
GO

Alter Table dbo.TreatmentBMPAttributeType
Alter Column TreatmentBMPAttributeTypePurposeID int not null
Alter Table dbo.TreatmentBMPAttributeType
Alter Column TreatmentBMPAttributeTypeDescription varchar(200) null