create table dbo.StormwaterJurisdictionBMPPublicVisibilityType (
	StormwaterJurisdictionBMPPublicVisibilityTypeID int not null constraint PK_StormwaterJurisdictionBMPPublicVisibilityType_StormwaterJurisdictionBMPPublicVisibilityTypeID primary key,
	StormwaterJurisdictionBMPPublicVisibilityTypeName varchar(80) not null constraint AK_StormwaterJurisdictionBMPPublicVisibilityType_StormwaterJurisdictionBMPPublicVisibilityTypeName unique,
	StormwaterJurisdictionBMPPublicVisibilityTypeDisplayName varchar(80) not null constraint AK_StormwaterJurisdictionBMPPublicVisibilityType_StormwaterJurisdictionBMPPublicVisibilityTypeDisplayName unique
)

insert into dbo.StormwaterJurisdictionBMPPublicVisibilityType (StormwaterJurisdictionBMPPublicVisibilityTypeID, StormwaterJurisdictionBMPPublicVisibilityTypeName, StormwaterJurisdictionBMPPublicVisibilityTypeDisplayName)
values (1, 'VerifiedOnly', 'Verified Only'),
(2, 'None', 'None')

alter table dbo.StormwaterJurisdiction
add StormwaterJurisdictionBMPPublicVisibilityTypeID int null
go

update dbo.StormwaterJurisdiction
set StormwaterJurisdictionBMPPublicVisibilityTypeID = 1

alter table dbo.StormwaterJurisdiction
alter column StormwaterJurisdictionBMPPublicVisibilityTypeID int not null 

alter table dbo.StormwaterJurisdiction
add constraint FK_StormwaterJurisdiction_StormwaterJurisdictionBMPPublicVisibilityType_StormwaterJurisdictionBMPPublicVisibilityTypeID foreign key (StormwaterJurisdictionBMPPublicVisibilityTypeID) references dbo.StormwaterJurisdictionBMPPublicVisibilityType (StormwaterJurisdictionBMPPublicVisibilityTypeID)