drop table if exists dbo.gt_pk_metadata
go

CREATE TABLE [dbo].[gt_pk_metadata](
	[table_schema] [varchar](32) NOT NULL,
	[table_name] [varchar](32) NOT NULL,
	[pk_column] [varchar](32) NOT NULL,
	[pk_column_idx] [int] NULL,
	[pk_policy] [varchar](32) NULL,
	[pk_sequence] [varchar](64) NULL,
UNIQUE NONCLUSTERED 
(
	[table_schema] ASC,
	[table_name] ASC,
	[pk_column] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[gt_pk_metadata]  WITH CHECK ADD CHECK  (([pk_policy]='autogenerated' OR [pk_policy]='assigned' OR [pk_policy]='sequence'))
GO

insert into dbo.gt_pk_metadata (table_schema, table_name, pk_column, pk_column_idx, pk_policy, pk_sequence)
values
('dbo','vGeoServerDelineation','PrimaryKey',NULL,NULL,NULL)