alter table dbo.TreatmentBMPTypeAttributeType
add constraint AK_TreatmentBMPTypeAttributeType_TreatmentBMPTypeAttributeTypeID_TenantID
unique (TreatmentBMPTypeAttributeTypeID, TenantID)

create table dbo.MaintenanceRecordObservation​​(
MaintenanceRecordObservationID int not null identity(1,1)
	constraint PK_MaintenanceRecordObservation_MaintenanceRecordObservationID primary key,
TenantID int not null
	constraint FK_MaintenanceRecordObservation_Tenant_TenantID foreign key references dbo.Tenant(TenantID),
​MaintenanceRecordID int not null
	constraint FK_MaintenanceRecordObservation_MaintenanceRecord_MaintenanceRecordID foreign key references dbo.MaintenanceRecord(MaintenanceRecordID),
TreatmentBMPTypeAttributeTypeID int not null
	constraint FK_MaintenanceRecordObservation_TreatmentBMPTypeAttributeType_TreatmentBMPTypeAttributeTypeID
	foreign key references dbo.TreatmentBMPTypeAttributeType(TreatmentBMPTypeAttributeTypeID),
TreatmentBMPTypeID int not null
	constraint FK_MaintenanceRecordObservation_TreatmentBMPType_TreatmentBMPTypeID foreign key references dbo.TreatmentBMPType(TreatmentBMPTypeID),
TreatmentBMPAttributeTypeID int not null
	constraint FK_MaintenanceRecordObservation_TreatmentBMPAttributeType_TreatmentBMPAttributeTypeID foreign key references dbo.TreatmentBMPAttributeType(TreatmentBMPAttributeTypeID),

constraint FK_MaintenanceRecordObservation_MaintenanceRecord_MaintenanceRecordID_TenantID foreign key (MaintenanceRecordID, TenantID) references dbo.MaintenanceRecord(MaintenanceRecordID, TenantID),
constraint FK_MaintenanceRecordObservation_TreatmentBMPTypeAttributeType_TreatmentBMPTypeAttributeTypeID_TenantID
	foreign key (TreatmentBMPTypeAttributeTypeID, TenantID) references dbo.TreatmentBMPTypeAttributeType(TreatmentBMPTypeAttributeTypeID, TenantID),
constraint FK_MaintenanceRecordObservation_TreatmentBMPType_TreatmentBMPTypeID_TenantID foreign key (TreatmentBMPTypeID, TenantID) references dbo.TreatmentBMPType(TreatmentBMPTypeID, TenantID),
constraint FK_MaintenanceRecordObservation_TreatmentBMPAttributeType_TreatmentBMPAttributeTypeID_TenantID foreign key (TreatmentBMPAttributeTypeID, TenantID) references dbo.TreatmentBMPAttributeType(TreatmentBMPAttributeTypeID, TenantID),
constraint FK_MaintenanceRecordObservation_TreatmentBMPTypeAttributeType_TreatmentBMPTypeID_TreatmentBMPAttributeTypeID
	foreign key (TreatmentBMPTypeID, TreatmentBMPAttributeTypeID) references dbo.TreatmentBMPTypeAttributeType(TreatmentBMPTypeID, TreatmentBMPAttributeTypeID)
)

