DROP INDEX [SPATIAL_Parcel_ParcelGeometry] ON [dbo].[Parcel]
GO
CREATE SPATIAL INDEX [SPATIAL_Parcel_ParcelGeometry] ON [dbo].[Parcel]
(
	[ParcelGeometry]
)USING  GEOMETRY_AUTO_GRID 
WITH (BOUNDING_BOX =(5993240, 2087140, 6207830, 2292500), 
CELLS_PER_OBJECT = 8, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE SPATIAL INDEX [SPATIAL_ParcelStaging_ParcelStagingGeometry] ON [dbo].[ParcelStaging]
(
	[ParcelStagingGeometry]
)USING  GEOMETRY_AUTO_GRID 
WITH (BOUNDING_BOX =(5993240, 2087140, 6207830, 2292500), 
CELLS_PER_OBJECT = 8, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



