create table dbo.WaterQualityManagementPlanDocumentType(
WaterQualityManagementPlanDocumentTypeID int not null constraint PK_WaterQualityManagementPlanDocumentType_WaterQualityManagementPlanDocumentTypeID Primary Key,
WaterQualityManagementPlanDocumentTypeName varchar(100) not null constraint AK_WaterQualityManagementPlanDocumentType_WaterQualityManagementPlanDocumentTypeName unique,
WaterQualityManagementPlanDocumentTypeDisplayName varchar(100) not null constraint AK_WaterQualityManagementPlanDocumentType_WaterQualityManagementPlanDocumentTypeDisplayName unique,
IsRequired bit not null
)
go

alter table dbo.WaterQualityManagementPlanDocument
add WaterQualityManagementPlanDocumentTypeID int null
go

alter table dbo.WaterQualityManagementPlanDocument
add constraint FK_WaterQualityManagementPlanDocument_WaterQualityManagementPlanDocumentType_WaterQualityManagementPlanDocumentTypeID
	foreign key (WaterQualityManagementPlanDocumentTypeID)
	references dbo.WaterQualityManagementPlanDocumentType(WaterQualityManagementPlanDocumentTypeID)

