create table dbo.OnlandVisualTrashAssessmentArea(
OnlandVisualTrashAssessmentAreaID int not null identity(1,1) constraint PK_OnlandVisualTrashAssessmentArea_OnlandVisualTrashAssessmentAreaID primary key,
--OnlandVisualTrashAssessmentAreaName varchar(100) not null ,
--StormwaterJurisdictionID int not null constraint FK_OnlandVisualTrashAssessmentArea_StormwaterJurisdiction_StormwaterJurisdictionID foreign key references dbo.StormwaterJurisdiction(StormwaterJurisdictionID),
OnlandVisualTrashAssessmentAreaGeometry geometry not null --,
--Constraint AK_OnlandVisualTrashAssessmentArea_OnlandVisualTrashAssessmentAreaName_StormwaterJurisdictionID unique(OnlandVisualTrashAssessmentAreaName, StormwaterJurisdictionID)
)

Alter Table dbo.OnlandVisualTrashAssessment
Add OnlandVisualTrashAssessmentAreaID int null
Go

Alter Table dbo.OnlandVisualTrashAssessment
Add Constraint FK_OnlandVisualTrashAssessment_OnlandVisualTrashAssessmentArea_OnlandVisualTrashAssessmentAreaID
Foreign Key (OnlandVisualTrashAssessmentAreaID) references dbo.OnlandVisualTrashAssessmentArea(OnlandVisualTrashAssessmentAreaID)