Alter Table dbo.OnlandVisualTrashAssessmentArea
Add Constraint AK_OnlandVisualTrashAssessmentArea_OnlandVisualTrashAssessmentAreaID_StormwaterJurisdictionID unique (OnlandVisualTrashAssessmentAreaID, StormwaterJurisdictionID)
Go

Alter Table dbo.OnlandVisualTrashAssessment
Add Constraint FK_OnlandVisualTrashAssessment_OnlandVisualTrashAssessmentArea_OnlandVisualTrashAssessmentAreaID_StormwaterJurisdictionID
Foreign Key (OnlandVisualTrashAssessmentAreaID, StormwaterJurisdictionID) references dbo.OnlandVisualTrashAssessmentArea(OnlandVisualTrashAssessmentAreaID, StormwaterJurisdictionID)
Go