Create Table dbo.OnlandVisualTrashAssessmentObservationPhoto(
OnlandVisualTrashAssessmentObservationPhotoID int not null identity(1,1) constraint PK_OnlandVisualTrashAssessmentObservationPhoto_OnlandVisualTrashAssessmentObservationPhotoID primary key,
FileResourceID int not null constraint FK_OnlandVisualTrashAssessmentObservationPhoto_FileResource_FileResourceID
	Foreign Key references dbo.FileResource(FileResourceID),
OnlandVisualTrashAssessmentObservationID int not null constraint FK_OnlandVisualTrashAssessmentObservationPhoto_OnlandVisualTrashAssessmentObservation_OnlandVisualTrashAssessmentObservationID
	Foreign Key references dbo.OnlandVisualTrashAssessmentObservation(OnlandVisualTrashAssessmentObservationID)
)