Create Table dbo.OnlandVisualTrashAssessmentObservationPhoto(
OnlandVisualTrashAssessmentObservationPhotoID int not null identity(1,1) constraint PK_OnlandVisualTrashAssessmentObservationPhoto_OnlandVisualTrashAssessmentObservationPhotoID primary key,
FileResourceID int not null constraint FK_OnlandVisualTrashAssessmentObservationPhoto_FileResource_FileResourceID
	Foreign Key references dbo.FileResource(FileResourceID),
OnlandVisualTrashAssessmentObservationID int not null constraint FK_OnlandVisualTrashAssessmentObservationPhoto_OnlandVisualTrashAssessmentObservation_OnlandVisualTrashAssessmentObservationID
	Foreign Key references dbo.OnlandVisualTrashAssessmentObservation(OnlandVisualTrashAssessmentObservationID)
)

Create Table dbo.OnlandVisualTrashAssessmentObservationPhotoStaging(
OnlandVisualTrashAssessmentObservationPhotoStagingID int not null identity(1,1) constraint PK_OnlandVisualTrashAssessmentObservationPhotoStaging_OnlandVisualTrashAssessmentObservationPhotoStagingID primary key,
FileResourceID int not null constraint FK_OnlandVisualTrashAssessmentObservationPhotoStaging_FileResource_FileResourceID
	Foreign Key references dbo.FileResource(FileResourceID),
OnlandVisualTrashAssessmentID int not null constraint FK_OnlandVisualTrashAssessmentObservationPhotoStaging_OnlandVisualTrashAssessment_OnlandVisualTrashAssessmentID
	Foreign Key references dbo.OnlandVisualTrashAssessment(OnlandVisualTrashAssessmentID)
)