create table dbo.OnlandVisualTrashAssessmentScore (
OnlandVisualTrashAssessmentScoreID int not null constraint PK_OnlandVisualTrashAssessmentScore_OnlandVisualTrashAssessmentScoreID primary key,
OnlandVisualTrashAssessmentScoreName varchar(1) constraint AK_OnlandVisualTrashAssessmentScore_OnlandVisualTrashAssessmentScoreName unique,
OnlandVisualTrashAssessmentScoreDisplayName varchar(1) constraint AK_OnlandVisualTrashAssessmentScore_OnlandVisualTrashAssessmentScoreDisplayName unique
)
go

Alter Table dbo.OnlandVisualTrashAssessment
Add OnlandVisualTrashAssessmentScoreID int null
	constraint FK_OnlandVisualTrashAssessment_OnlandVisualTrashAssessmentScore_OnlandVisualTrashAssessmentScoreID
	foreign key references dbo.OnlandVisualTrashAssessmentScore(OnlandVisualTrashAssessmentScoreID)
go

Alter Table dbo.OnlandVisualTrashAssessment
Add Constraint CK_OnlandVisualTrashAssessment_CompletedAssessmentMustHaveScore
Check (not (OnlandVisualTrashAssessmentScoreID is null and OnlandVisualTrashAssessmentStatusID = 2))
