
/* for Neptune.dbo.County.CountyFeature */ -- Table empty index not created: SPATIAL_County_CountyFeature
/* for Neptune.dbo.Delineation.DelineationGeometry */ IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_Delineation_DelineationGeometry') create spatial index SPATIAL_Delineation_DelineationGeometry on Neptune.dbo.Delineation(DelineationGeometry) with (BOUNDING_BOX=(-119, 33, -117, 34))
/* for Neptune.dbo.LandUseBlock.LandUseBlockGeometry */ IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_LandUseBlock_LandUseBlockGeometry') create spatial index SPATIAL_LandUseBlock_LandUseBlockGeometry on Neptune.dbo.LandUseBlock(LandUseBlockGeometry) with (BOUNDING_BOX=(-119, 33, -117, 34))
/* for Neptune.dbo.ModeledCatchment.ModeledCatchmentGeometry */ -- Table empty index not created: SPATIAL_ModeledCatchment_ModeledCatchmentGeometry
/* for Neptune.dbo.NetworkCatchment.CatchmentGeometry */ IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_NetworkCatchment_CatchmentGeometry') create spatial index SPATIAL_NetworkCatchment_CatchmentGeometry on Neptune.dbo.NetworkCatchment(CatchmentGeometry) with (BOUNDING_BOX=(-119, 33, -117, 34))
/* for Neptune.dbo.OnlandVisualTrashAssessment.DraftGeometry */ IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_OnlandVisualTrashAssessment_DraftGeometry') create spatial index SPATIAL_OnlandVisualTrashAssessment_DraftGeometry on Neptune.dbo.OnlandVisualTrashAssessment(DraftGeometry) with (BOUNDING_BOX=(-118, 33, -117, 34))
/* for Neptune.dbo.OnlandVisualTrashAssessmentArea.OnlandVisualTrashAssessmentAreaGeometry */ IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_OnlandVisualTrashAssessmentArea_OnlandVisualTrashAssessmentAreaGeometry') create spatial index SPATIAL_OnlandVisualTrashAssessmentArea_OnlandVisualTrashAssessmentAreaGeometry on Neptune.dbo.OnlandVisualTrashAssessmentArea(OnlandVisualTrashAssessmentAreaGeometry) with (BOUNDING_BOX=(-118, 33, -117, 34))
/* for Neptune.dbo.OnlandVisualTrashAssessmentObservation.LocationPoint */ IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_OnlandVisualTrashAssessmentObservation_LocationPoint') create spatial index SPATIAL_OnlandVisualTrashAssessmentObservation_LocationPoint on Neptune.dbo.OnlandVisualTrashAssessmentObservation(LocationPoint) with (BOUNDING_BOX=(-118, 33, -117, 34))
/* for Neptune.dbo.Parcel.ParcelGeometry */ IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_Parcel_ParcelGeometry') create spatial index SPATIAL_Parcel_ParcelGeometry on Neptune.dbo.Parcel(ParcelGeometry) with (BOUNDING_BOX=(-119, 33, -117, 34))
/* for Neptune.dbo.StateProvince.StateProvinceFeature */ IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_StateProvince_StateProvinceFeature') create spatial index SPATIAL_StateProvince_StateProvinceFeature on Neptune.dbo.StateProvince(StateProvinceFeature) with (BOUNDING_BOX=(-121, 38, -119, 40))
/* for Neptune.dbo.StateProvince.StateProvinceFeatureForAnalysis */ IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_StateProvince_StateProvinceFeatureForAnalysis') create spatial index SPATIAL_StateProvince_StateProvinceFeatureForAnalysis on Neptune.dbo.StateProvince(StateProvinceFeatureForAnalysis) with (BOUNDING_BOX=(-125, 35, -115, 43))
/* for Neptune.dbo.StormwaterJurisdiction.StormwaterJurisdictionGeometry */ IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_StormwaterJurisdiction_StormwaterJurisdictionGeometry') create spatial index SPATIAL_StormwaterJurisdiction_StormwaterJurisdictionGeometry on Neptune.dbo.StormwaterJurisdiction(StormwaterJurisdictionGeometry) with (BOUNDING_BOX=(-119, 33, -117, 34))
/* for Neptune.dbo.TreatmentBMP.LocationPoint */ IF NOT EXISTS (SELECT name FROM sysindexes WHERE name = 'SPATIAL_TreatmentBMP_LocationPoint') create spatial index SPATIAL_TreatmentBMP_LocationPoint on Neptune.dbo.TreatmentBMP(LocationPoint) with (BOUNDING_BOX=(-123, 33, -117, 46))
