Alter table dbo.OnlandVisualTrashAssessmentArea
Add TransectBackingAssessmentID int null
constraint FK_OnlandVisualTrashAssessmentArea_OnlandVisualTrashAssessment_TransectBackingAssessmentID_OnlandVisualTrashAssessmentID references dbo.OnlandVisualTrashAssessment(OnlandVisualTrashAssessmentID)
