Alter Table dbo.TrashGeneratingUnitAdjustment
Drop constraint FK_TrashGeneratingUnitAdjustment_OnlandVisualTrashAssessmentArea_AdjustedOnlandVisualTrashAssessmentAreaID_OnlandVisualTrashAsse

Alter Table dbo.TrashGeneratingUnitAdjustment
Drop constraint FK_TrashGeneratingUnitAdjustment_Delineation_AdjustedDelineationID_DelineationID