Alter Table dbo.TrashGeneratingUnit
Drop Constraint FK_TrashGeneratingUnit_OnlandVisualTrashAssessmentArea_OnlandVisualTrashAssessmentAreaID

Alter Table dbo.TrashGeneratingUnit
Drop Constraint FK_TrashGeneratingUnit_TreatmentBMP_TreatmentBMPID