if exists (select * from dbo.sysobjects where id = object_id('dbo.vProjectLoadReducingResult'))
    drop view dbo.vProjectLoadReducingResult
go

create view dbo.vProjectLoadReducingResult
as

select  ProjectNereidResultID as PrimaryKey,        
        ProjectNereidResultID,
        p.ProjectID,
        p.ProjectName,
		sjo.OrganizationName as JurisdictionName,
		o.OrganizationName as OrganizationName,
        IsBaselineCondition,
        tbmp.TreatmentBMPID,
        tbmp.TreatmentBMPName,
        pnr.WaterQualityManagementPlanID,
        pnr.RegionalSubbasinID,
        DelineationID,
        NodeID,
        --FullResponse,
        LastUpdate,
        EffectiveAreaAcres,
        DesignStormDepth85thPercentile,
        DesignVolume85thPercentile,
        WetWeatherInflow as WetWeatherInflow,
        WetWeatherTreated as WetWeatherTreated,
        WetWeatherRetained as WetWeatherRetained,
        WetWeatherUntreated as WetWeatherUntreated,
        WetWeatherTSSReduced * uc.PoundsToKilogramsFactor as WetWeatherTSSReduced,
        WetWeatherTNReduced * uc.PoundsToKilogramsFactor as WetWeatherTNReduced,
        WetWeatherTPReduced * uc.PoundsToKilogramsFactor as WetWeatherTPReduced,
        WetWeatherFCReduced / uc.BillionsFactor as WetWeatherFCReduced,
        WetWeatherTCuReduced * uc.PoundsToGramsFactor as WetWeatherTCuReduced,
        WetWeatherTPbReduced * uc.PoundsToGramsFactor as WetWeatherTPbReduced,
        WetWeatherTZnReduced * uc.PoundsToGramsFactor as WetWeatherTZnReduced,
        WetWeatherTSSInflow * uc.PoundsToKilogramsFactor as WetWeatherTSSInflow,
        WetWeatherTNInflow * uc.PoundsToKilogramsFactor as WetWeatherTNInflow,
        WetWeatherTPInflow * uc.PoundsToKilogramsFactor as WetWeatherTPInflow,
        WetWeatherFCInflow / uc.BillionsFactor as WetWeatherFCInflow,
        WetWeatherTCuInflow * uc.PoundsToGramsFactor as WetWeatherTCuInflow,
        WetWeatherTPbInflow * uc.PoundsToGramsFactor as WetWeatherTPbInflow,
        WetWeatherTZnInflow * uc.PoundsToGramsFactor as WetWeatherTZnInflow,
        SummerDryWeatherInflow as SummerDryWeatherInflow,
        SummerDryWeatherTreated as SummerDryWeatherTreated,
        SummerDryWeatherRetained as SummerDryWeatherRetained,
        SummerDryWeatherUntreated as SummerDryWeatherUntreated,
        SummerDryWeatherTSSReduced * uc.PoundsToKilogramsFactor as SummerDryWeatherTSSReduced,
        SummerDryWeatherTNReduced * uc.PoundsToKilogramsFactor as SummerDryWeatherTNReduced,
        SummerDryWeatherTPReduced * uc.PoundsToKilogramsFactor as SummerDryWeatherTPReduced,
        SummerDryWeatherFCReduced / uc.BillionsFactor as SummerDryWeatherFCReduced,
        SummerDryWeatherTCuReduced * uc.PoundsToGramsFactor as SummerDryWeatherTCuReduced,
        SummerDryWeatherTPbReduced * uc.PoundsToGramsFactor as SummerDryWeatherTPbReduced,
        SummerDryWeatherTZnReduced * uc.PoundsToGramsFactor as SummerDryWeatherTZnReduced,
        SummerDryWeatherTSSInflow * uc.PoundsToKilogramsFactor as SummerDryWeatherTSSInflow,
        SummerDryWeatherTNInflow * uc.PoundsToKilogramsFactor as SummerDryWeatherTNInflow,
        SummerDryWeatherTPInflow * uc.PoundsToKilogramsFactor as SummerDryWeatherTPInflow,
        SummerDryWeatherFCInflow / uc.BillionsFactor as SummerDryWeatherFCInflow,
        SummerDryWeatherTCuInflow * uc.PoundsToGramsFactor as SummerDryWeatherTCuInflow,
        SummerDryWeatherTPbInflow * uc.PoundsToGramsFactor as SummerDryWeatherTPbInflow,
        SummerDryWeatherTZnInflow * uc.PoundsToGramsFactor as SummerDryWeatherTZnInflow,
        WinterDryWeatherInflow as WinterDryWeatherInflow,
        WinterDryWeatherTreated as WinterDryWeatherTreated,
        WinterDryWeatherRetained as WinterDryWeatherRetained,
        WinterDryWeatherUntreated as WinterDryWeatherUntreated,
        WinterDryWeatherTSSReduced * uc.PoundsToKilogramsFactor as WinterDryWeatherTSSReduced,
        WinterDryWeatherTNReduced * uc.PoundsToKilogramsFactor as WinterDryWeatherTNReduced,
        WinterDryWeatherTPReduced * uc.PoundsToKilogramsFactor as WinterDryWeatherTPReduced,
        WinterDryWeatherFCReduced / uc.BillionsFactor as WinterDryWeatherFCReduced,
        WinterDryWeatherTCuReduced * uc.PoundsToGramsFactor as WinterDryWeatherTCuReduced,
        WinterDryWeatherTPbReduced * uc.PoundsToGramsFactor as WinterDryWeatherTPbReduced,
        WinterDryWeatherTZnReduced * uc.PoundsToGramsFactor as WinterDryWeatherTZnReduced,
        WinterDryWeatherTSSInflow * uc.PoundsToKilogramsFactor as WinterDryWeatherTSSInflow,
        WinterDryWeatherTNInflow * uc.PoundsToKilogramsFactor as WinterDryWeatherTNInflow,
        WinterDryWeatherTPInflow * uc.PoundsToKilogramsFactor as WinterDryWeatherTPInflow,
        WinterDryWeatherFCInflow / uc.BillionsFactor as WinterDryWeatherFCInflow,
        WinterDryWeatherTCuInflow * uc.PoundsToGramsFactor as WinterDryWeatherTCuInflow,
        WinterDryWeatherTPbInflow * uc.PoundsToGramsFactor as WinterDryWeatherTPbInflow,
        WinterDryWeatherTZnInflow * uc.PoundsToGramsFactor as WinterDryWeatherTZnInflow

        from dbo.ProjectNereidResult pnr
        join dbo.Project p on pnr.ProjectID = p.ProjectID
		join dbo.StormwaterJurisdiction sj on p.StormwaterJurisdictionID = sj.StormwaterJurisdictionID
		join dbo.Organization sjo on sj.OrganizationID = sjo.OrganizationID
		join dbo.Organization o on p.OrganizationID = o.OrganizationID
        join dbo.TreatmentBMP tbmp on pnr.TreatmentBMPID = tbmp.TreatmentBMPID
        cross apply openjson(fullresponse) 
        with (
            WetWeatherInflow float '$.runoff_volume_cuft_inflow',
            WetWeatherTreated float '$.runoff_volume_cuft_treated',
            WetWeatherRetained float '$.runoff_volume_cuft_retained',
            WetWeatherUntreated float '$.runoff_volume_cuft_bypassed',
            WetWeatherTSSReduced float '$.TSS_load_lbs_removed',
            WetWeatherTNReduced float '$.TN_load_lbs_removed',
            WetWeatherTPReduced float '$.TP_load_lbs_removed',
            WetWeatherFCReduced float '$.FC_load_mpn_removed',
            WetWeatherTCuReduced float '$.TCu_load_lbs_removed',
            WetWeatherTPbReduced float '$.TPb_load_lbs_removed',
            WetWeatherTZnReduced float '$.TZn_load_lbs_removed',
            WetWeatherTSSInflow float '$.TSS_load_lbs_inflow',
            WetWeatherTNInflow float '$.TN_load_lbs_inflow',
            WetWeatherTPInflow float '$.TP_load_lbs_inflow',
            WetWeatherFCInflow float '$.FC_load_mpn_inflow',
            WetWeatherTCuInflow float '$.TCu_load_lbs_inflow',
            WetWeatherTPbInflow float '$.TPb_load_lbs_inflow',
            WetWeatherTZnInflow float '$.TZn_load_lbs_inflow',
            SummerDryWeatherInflow float '$.summer_dry_weather_flow_cuft_inflow',
            SummerDryWeatherTreated float '$.summer_dry_weather_flow_cuft_treated',
            SummerDryWeatherRetained float '$.summer_dry_weather_flow_cuft_retained',
            SummerDryWeatherUntreated float '$.summer_dry_weather_flow_cuft_bypassed',
            SummerDryWeatherTSSReduced float '$.summer_dwTSS_load_lbs_removed',
            SummerDryWeatherTNReduced float '$.summer_dwTN_load_lbs_removed',
            SummerDryWeatherTPReduced float '$.summer_dwTP_load_lbs_removed',
            SummerDryWeatherFCReduced float '$.summer_dwFC_load_mpn_removed',
            SummerDryWeatherTCuReduced float '$.summer_dwTCu_load_lbs_removed',
            SummerDryWeatherTPbReduced float '$.summer_dwTPb_load_lbs_removed',
            SummerDryWeatherTZnReduced float '$.summer_dwTZn_load_lbs_removed',
            SummerDryWeatherTSSInflow float '$.summer_dwTSS_load_lbs_inflow',
            SummerDryWeatherTNInflow float '$.summer_dwTN_load_lbs_inflow',
            SummerDryWeatherTPInflow float '$.summer_dwTP_load_lbs_inflow',
            SummerDryWeatherFCInflow float '$.summer_dwFC_load_mpn_inflow',
            SummerDryWeatherTCuInflow float '$.summer_dwTCu_load_lbs_inflow',
            SummerDryWeatherTPbInflow float '$.summer_dwTPb_load_lbs_inflow',
            SummerDryWeatherTZnInflow float '$.summer_dwTZn_load_lbs_inflow',
            WinterDryWeatherInflow float '$.winter_dry_weather_flow_cuft_inflow',
            WinterDryWeatherTreated float '$.winter_dry_weather_flow_cuft_treated',
            WinterDryWeatherRetained float '$.winter_dry_weather_flow_cuft_retained',
            WinterDryWeatherUntreated float '$.winter_dry_weather_flow_cuft_bypassed',
            WinterDryWeatherTSSReduced float '$.winter_dwTSS_load_lbs_removed',
            WinterDryWeatherTNReduced float '$.winter_dwTN_load_lbs_removed',
            WinterDryWeatherTPReduced float '$.winter_dwTP_load_lbs_removed',
            WinterDryWeatherFCReduced float '$.winter_dwFC_load_mpn_removed',
            WinterDryWeatherTCuReduced float '$.winter_dwTCu_load_lbs_removed',
            WinterDryWeatherTPbReduced float '$.winter_dwTPb_load_lbs_removed',
            WinterDryWeatherTZnReduced float '$.winter_dwTZn_load_lbs_removed',
            WinterDryWeatherTSSInflow float '$.winter_dwTSS_load_lbs_inflow',
            WinterDryWeatherTNInflow float '$.winter_dwTN_load_lbs_inflow',
            WinterDryWeatherTPInflow float '$.winter_dwTP_load_lbs_inflow',
            WinterDryWeatherFCInflow float '$.winter_dwFC_load_mpn_inflow',
            WinterDryWeatherTCuInflow float '$.winter_dwTCu_load_lbs_inflow',
            WinterDryWeatherTPbInflow float '$.winter_dwTPb_load_lbs_inflow',
            WinterDryWeatherTZnInflow float '$.winter_dwTZn_load_lbs_inflow',
            EffectiveAreaAcres float '$.eff_area_acres_cumul',
            DesignStormDepth85thPercentile float '$.design_storm_depth_inches',
            DesignVolume85thPercentile float '$.design_volume_cuft_cumul'
        ) as ModelResults
        cross join dbo.vModelingResultUnitConversion uc

GO
/*
select * from dbo.vProjectLoadReducingResult where ProjectID = 14
*/