if exists (select * from dbo.sysobjects where id = object_id('dbo.vProjectModelingResults'))
    drop view dbo.vProjectModelingResults
go

create view dbo.vProjectModelingResults
as

with UnitConversions(PoundsToKilogramsFactor, PoundsToGramsFactor)
as
(
    select 0.453592 as PoundsToKilogramsFactor, 453.59 as PoundsToGramsFactor
)
select  ProjectNereidResultID as PrimaryKey,        
        ProjectNereidResultID,
        p.ProjectID,
        p.ProjectName,
        IsBaselineCondition,
        tbmp.TreatmentBMPID,
        tbmp.TreatmentBMPName,
        pnr.WaterQualityManagementPlanID,
        pnr.RegionalSubbasinID,
        DelineationID,
        NodeID,
        --FullResponse,
        LastUpdate,
        WetWeatherInflow as WetWeatherInflow,
        WetWeatherTreated as WetWeatherTreated,
        WetWeatherRetained as WetWeatherRetained,
        WetWeatherUntreated as WetWeatherUntreated,
        WetWeatherTSSRemoved * UnitConversions.PoundsToKilogramsFactor as WetWeatherTSSRemoved,
        WetWeatherTNRemoved * UnitConversions.PoundsToKilogramsFactor as WetWeatherTNRemoved,
        WetWeatherTPRemoved * UnitConversions.PoundsToKilogramsFactor as WetWeatherTPRemoved,
        WetWeatherFCRemoved / 1e9 as WetWeatherFCRemoved,
        WetWeatherTCuRemoved * UnitConversions.PoundsToGramsFactor as WetWeatherTCuRemoved,
        WetWeatherTPbRemoved * UnitConversions.PoundsToGramsFactor as WetWeatherTPbRemoved,
        WetWeatherTZnRemoved * UnitConversions.PoundsToGramsFactor as WetWeatherTZnRemoved,
        WetWeatherTSSInflow * UnitConversions.PoundsToKilogramsFactor as WetWeatherTSSInflow,
        WetWeatherTNInflow * UnitConversions.PoundsToKilogramsFactor as WetWeatherTNInflow,
        WetWeatherTPInflow * UnitConversions.PoundsToKilogramsFactor as WetWeatherTPInflow,
        WetWeatherFCInflow / 1e9 as WetWeatherFCInflow,
        WetWeatherTCuInflow * UnitConversions.PoundsToGramsFactor as WetWeatherTCuInflow,
        WetWeatherTPbInflow * UnitConversions.PoundsToGramsFactor as WetWeatherTPbInflow,
        WetWeatherTZnInflow * UnitConversions.PoundsToGramsFactor as WetWeatherTZnInflow,
        SummerDryWeatherInflow as SummerDryWeatherInflow,
        SummerDryWeatherTreated as SummerDryWeatherTreated,
        SummerDryWeatherRetained as SummerDryWeatherRetained,
        SummerDryWeatherUntreated as SummerDryWeatherUntreated,
        SummerDryWeatherTSSRemoved * UnitConversions.PoundsToKilogramsFactor as SummerDryWeatherTSSRemoved,
        SummerDryWeatherTNRemoved * UnitConversions.PoundsToKilogramsFactor as SummerDryWeatherTNRemoved,
        SummerDryWeatherTPRemoved * UnitConversions.PoundsToKilogramsFactor as SummerDryWeatherTPRemoved,
        SummerDryWeatherFCRemoved / 1e9 as SummerDryWeatherFCRemoved,
        SummerDryWeatherTCuRemoved * UnitConversions.PoundsToGramsFactor as SummerDryWeatherTCuRemoved,
        SummerDryWeatherTPbRemoved * UnitConversions.PoundsToGramsFactor as SummerDryWeatherTPbRemoved,
        SummerDryWeatherTZnRemoved * UnitConversions.PoundsToGramsFactor as SummerDryWeatherTZnRemoved,
        SummerDryWeatherTSSInflow * UnitConversions.PoundsToKilogramsFactor as SummerDryWeatherTSSInflow,
        SummerDryWeatherTNInflow * UnitConversions.PoundsToKilogramsFactor as SummerDryWeatherTNInflow,
        SummerDryWeatherTPInflow * UnitConversions.PoundsToKilogramsFactor as SummerDryWeatherTPInflow,
        SummerDryWeatherFCInflow / 1e9 as SummerDryWeatherFCInflow,
        SummerDryWeatherTCuInflow * UnitConversions.PoundsToGramsFactor as SummerDryWeatherTCuInflow,
        SummerDryWeatherTPbInflow * UnitConversions.PoundsToGramsFactor as SummerDryWeatherTPbInflow,
        SummerDryWeatherTZnInflow * UnitConversions.PoundsToGramsFactor as SummerDryWeatherTZnInflow,
        WinterDryWeatherInflow as WinterDryWeatherInflow,
        WinterDryWeatherTreated as WinterDryWeatherTreated,
        WinterDryWeatherRetained as WinterDryWeatherRetained,
        WinterDryWeatherUntreated as WinterDryWeatherUntreated,
        WinterDryWeatherTSSRemoved * UnitConversions.PoundsToKilogramsFactor as WinterDryWeatherTSSRemoved,
        WinterDryWeatherTNRemoved * UnitConversions.PoundsToKilogramsFactor as WinterDryWeatherTNRemoved,
        WinterDryWeatherTPRemoved * UnitConversions.PoundsToKilogramsFactor as WinterDryWeatherTPRemoved,
        WinterDryWeatherFCRemoved / 1e9 as WinterDryWeatherFCRemoved,
        WinterDryWeatherTCuRemoved * UnitConversions.PoundsToGramsFactor as WinterDryWeatherTCuRemoved,
        WinterDryWeatherTPbRemoved * UnitConversions.PoundsToGramsFactor as WinterDryWeatherTPbRemoved,
        WinterDryWeatherTZnRemoved * UnitConversions.PoundsToGramsFactor as WinterDryWeatherTZnRemoved,
        WinterDryWeatherTSSInflow * UnitConversions.PoundsToKilogramsFactor as WinterDryWeatherTSSInflow,
        WinterDryWeatherTNInflow * UnitConversions.PoundsToKilogramsFactor as WinterDryWeatherTNInflow,
        WinterDryWeatherTPInflow * UnitConversions.PoundsToKilogramsFactor as WinterDryWeatherTPInflow,
        WinterDryWeatherFCInflow / 1e9 as WinterDryWeatherFCInflow,
        WinterDryWeatherTCuInflow * UnitConversions.PoundsToGramsFactor as WinterDryWeatherTCuInflow,
        WinterDryWeatherTPbInflow * UnitConversions.PoundsToGramsFactor as WinterDryWeatherTPbInflow,
        WinterDryWeatherTZnInflow * UnitConversions.PoundsToGramsFactor as WinterDryWeatherTZnInflow

        from dbo.ProjectNereidResult pnr
        join dbo.Project p on pnr.ProjectID = p.ProjectID
        left join dbo.TreatmentBMP tbmp on pnr.TreatmentBMPID = tbmp.TreatmentBMPID
        cross apply openjson(fullresponse) 
        with (
            WetWeatherInflow float '$.runoff_volume_cuft_inflow',
            WetWeatherTreated float '$.runoff_volume_cuft_treated',
            WetWeatherRetained float '$.runoff_volume_cuft_retained',
            WetWeatherUntreated float '$.runoff_volume_cuft_bypassed',
            WetWeatherTSSRemoved float '$.TSS_load_lbs_removed',
            WetWeatherTNRemoved float '$.TN_load_lbs_removed',
            WetWeatherTPRemoved float '$.TP_load_lbs_removed',
            WetWeatherFCRemoved float '$.FC_load_mpn_removed',
            WetWeatherTCuRemoved float '$.TCu_load_lbs_removed',
            WetWeatherTPbRemoved float '$.TPb_load_lbs_removed',
            WetWeatherTZnRemoved float '$.TZn_load_lbs_removed',
            WetWeatherTSSInflow float '$.TSS_load_lbs_inflow',
            WetWeatherTNInflow float '$.TN_load_lbs_inflow',
            WetWeatherTPInflow float '$.TP_load_lbs_inflow',
            WetWeatherFCInflow float '$.FC_load_mpn_inflow',
            WetWeatherTCuInflow float '$.TCu_load_lbs_inflow',
            WetWeatherTPbInflow float '$.TPb_load_lbs_inflow',
            WetWeatherTZnInflow float '$.TZn_load_lbs_inflow',
            SummerDryWeatherInflow float '$.summer_dry_weather_flow_cuft_inflow',
            SummerDryWeatherTreated float '$.summer_dry_weather_flow_cuft_treated',
            SummerDryWeatherRetained float '$.summer_dry_weather_flow_cuft_retained',
            SummerDryWeatherUntreated float '$.summer_dry_weather_flow_cuft_bypassed',
            SummerDryWeatherTSSRemoved float '$.summer_dwTSS_load_lbs_removed',
            SummerDryWeatherTNRemoved float '$.summer_dwTN_load_lbs_removed',
            SummerDryWeatherTPRemoved float '$.summer_dwTP_load_lbs_removed',
            SummerDryWeatherFCRemoved float '$.summer_dwFC_load_mpn_removed',
            SummerDryWeatherTCuRemoved float '$.summer_dwTCu_load_lbs_removed',
            SummerDryWeatherTPbRemoved float '$.summer_dwTPb_load_lbs_removed',
            SummerDryWeatherTZnRemoved float '$.summer_dwTZn_load_lbs_removed',
            SummerDryWeatherTSSInflow float '$.summer_dwTSS_load_lbs_inflow',
            SummerDryWeatherTNInflow float '$.summer_dwTN_load_lbs_inflow',
            SummerDryWeatherTPInflow float '$.summer_dwTP_load_lbs_inflow',
            SummerDryWeatherFCInflow float '$.summer_dwFC_load_mpn_inflow',
            SummerDryWeatherTCuInflow float '$.summer_dwTCu_load_lbs_inflow',
            SummerDryWeatherTPbInflow float '$.summer_dwTPb_load_lbs_inflow',
            SummerDryWeatherTZnInflow float '$.summer_dwTZn_load_lbs_inflow',
            WinterDryWeatherInflow float '$.winter_dry_weather_flow_cuft_inflow',
            WinterDryWeatherTreated float '$.winter_dry_weather_flow_cuft_treated',
            WinterDryWeatherRetained float '$.winter_dry_weather_flow_cuft_retained',
            WinterDryWeatherUntreated float '$.winter_dry_weather_flow_cuft_bypassed',
            WinterDryWeatherTSSRemoved float '$.winter_dwTSS_load_lbs_removed',
            WinterDryWeatherTNRemoved float '$.winter_dwTN_load_lbs_removed',
            WinterDryWeatherTPRemoved float '$.winter_dwTP_load_lbs_removed',
            WinterDryWeatherFCRemoved float '$.winter_dwFC_load_mpn_removed',
            WinterDryWeatherTCuRemoved float '$.winter_dwTCu_load_lbs_removed',
            WinterDryWeatherTPbRemoved float '$.winter_dwTPb_load_lbs_removed',
            WinterDryWeatherTZnRemoved float '$.winter_dwTZn_load_lbs_removed',
            WinterDryWeatherTSSInflow float '$.winter_dwTSS_load_lbs_inflow',
            WinterDryWeatherTNInflow float '$.winter_dwTN_load_lbs_inflow',
            WinterDryWeatherTPInflow float '$.winter_dwTP_load_lbs_inflow',
            WinterDryWeatherFCInflow float '$.winter_dwFC_load_mpn_inflow',
            WinterDryWeatherTCuInflow float '$.winter_dwTCu_load_lbs_inflow',
            WinterDryWeatherTPbInflow float '$.winter_dwTPb_load_lbs_inflow',
            WinterDryWeatherTZnInflow float '$.winter_dwTZn_load_lbs_inflow'
        ) as ModelResults
        cross join UnitConversions

GO
/*
select * from dbo.vProjectModelingResults where ProjectID = 14
*/