create view dbo.vGeoServerOnlandVisualTrashAssessmentArea
as select area.OnlandVisualTrashAssessmentAreaID,
area.OnlandVisualTrashAssessmentAreaName,
area.StormwaterJurisdictionID,
area.OnlandVisualTrashAssessmentAreaGeometry,
area.OnlandVisualTrashAssessmentScoreID as Score
from dbo.OnlandVisualTrashAssessmentArea area join dbo.OnlandVisualTrashAssessmentScore score on area.OnlandVisualTrashAssessmentScoreID = score.OnlandVisualTrashAssessmentScoreID