{{ if eq .Values.global.env.name "prod" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-prod-configmap
data:
  SECRET_PATH: "/app/secrets/neptuneApiSecrets"
  DOCKER_BUILD_SOURCE: "."
  ASPNETCORE_ENVIRONMENT: "Production"
  APPINSIGHTS_INSTRUMENTATIONKEY: "{{ .Values.global.env.appInsightsInstrumentationKey }}"
  SitkaSupportEmail: "h2o.team@esassoc.com"
  DoNotReplyEmail: "donotreply@ocstormwatertools.org"
  SitkaEmailRedirect: ""
  KeystoneOpenIDUrl: "https://identity.sitkatech.com"
  KeystoneRedirectUrl: "https://{{ .Values.global.domains.web }}/create-user-callback"
  OcStormwaterToolsBaseUrl: "https://{{ .Values.global.domains.webmvc }}"
  PlanningModuleBaseUrl: "https://{{ .Values.global.domains.web }}"
  NereidUrl: "http://{{ .Values.global.domains.nereid }}"
  GDALAPIBaseUrl: "http://{{ .Values.global.domains.gdalApi }}"  
  OCGISBaseUrl: "https://ocgis.com/arcpub/rest/services/"
{{ end }}