apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nereid.fullname" . }}-qa-configmap
data:
  CELERY_BROKER_URL: "redis://neptune-nereid-redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://neptune-nereid-redis:6379/0"
  NEREID_ASYNC_MODE: "replace"
