version: '3.7'

services:
  hippocamp.api:
    image: hippocamp/api
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    ports:
      - "8211:80"
      - "8212:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8212
      - Kestrel__Certificates__Default__Path=/https/host.docker.internal.pfx
      - Kestrel__Certificates__Default__Password=password#1
    volumes:
      - ~/.aspnet/https:/https:ro

  # To use this locally, the connection string can just be "UseDevelopmentStorage=true" more info here: https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=docker-hub#well-known-storage-account-and-key
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000" # blob service
      # - "10001:10001" # queue service
      # - "10002:10002" # table service
    volumes:
      - c:/sitka/Hippocamp/azurite:/data