version: '3.7'

services:
  neptune.webmvc:
    image: neptune/webmvc
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    ports:
      - "6211:80"
      - "6212:443"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=6212
      - Kestrel__Certificates__Default__Path=/https/host.docker.internal.pfx
      - Kestrel__Certificates__Default__Password=password#1
    volumes:
      - ~/.aspnet/https:/https:ro
  
  geoserver:
    container_name: neptune_geoserver
    image: kartoza/geoserver:2.16.2
    entrypoint: /bin/bash /opt/geoserver/data_dir/sitka-geoserver-config/scripts/sitka-entry-point.sh
    environment:
      - ENABLE_JSONP=true
      - CATALINA_OPTS=-DALLOW_ENV_PARAMETRIZATION=true
      - STABLE_EXTENSIONS=sqlserver-plugin
      # default login is admin unless a different value is specified here
      - GEOSERVER_ADMIN_USER=admin
      # default password is geoserver unless specified differently in the secret
      - GEOSERVER_ADMIN_PASSWORD_SECRET=/run/secrets/GeoserverAdminPassword.txt
      - GEOSERVER_SQL_SERVER_PASSWORD_SECRET=/run/secrets/GeoserverSqlServerPassword.txt
      - GEOSERVER_CONFIG_DIRECTORY=/opt/geoserver/data_dir
    ports:
      - 127.0.0.1:8780:8080
    volumes:
      - c:/git/sitkatech/neptune/Neptune.GeoServer/data_dir:/opt/geoserver/data_dir
    secrets:
      - GeoserverSqlServerPassword.txt
      - GeoserverAdminPassword.txt

secrets:
  GeoserverSqlServerPassword.txt:
    file: C:\Sitka\Neptune\Geoserver\GeoserverSqlServerPassword.txt
      # using "file:"  allows you to mimic docker secrets on your dev machine by pointing to a plaintext file
  GeoserverAdminPassword.txt:
    file: C:\Sitka\Neptune\Geoserver\GeoserverAdminPassword.txt