version: '3.4'

services:
  neptune.webmvc:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - KEYSTONE_HOST=${KEYSTONE_HOST}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SITKA_EMAIL_REDIRECT=${SITKA_EMAIL_REDIRECT}
      - WEB_URL=${WEB_URL}
      - SECRET_PATH=${SECRET_PATH}
      - KEYSTONE_REDIRECT_URL=${KEYSTONE_REDIRECT_URL}
      - PlatformLongName=${PlatformLongName}
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - OcStormwaterToolsBaseUrl=${OcStormwaterToolsBaseUrl}
      - OcStormwaterToolsModelingBaseUrl=${OcStormwaterToolsModelingBaseUrl}
      - SitkaEmailRedirect=${SitkaEmailRedirect}
      - IsEmailEnabled=${IsEmailEnabled}
      - MailLogBcc=${MailLogBcc}
      - MaximumAllowedUploadFileSize=${MaximumAllowedUploadFileSize}
      - DatabaseServerName=${DatabaseServerName}
      - DatabaseName=${DatabaseName}
      - RecaptchaPublicKey=${RecaptchaPublicKey}
      - RecaptchaPrivateKey=${RecaptchaPrivateKey}
      - RecaptchaValidatorUrl=${RecaptchaValidatorUrl}
      - SitkaSupportEmail=${SitkaSupportEmail}
      - DoNotReplyEmail=${DoNotReplyEmail}
      - ApplicationDomain=${ApplicationDomain}
      - Ogr2OgrExecutable=${Ogr2OgrExecutable}
      - OgrInfoExecutable=${OgrInfoExecutable}
      - ReportingPeriodStartMonth=${ReportingPeriodStartMonth}
      - ReportingPeriodStartDay=${ReportingPeriodStartDay}
      - AnnualReportingContactPersonID=${AnnualReportingContactPersonID}
      - DefaultSupportPersonID=${DefaultSupportPersonID}
      - LogFileFolder=${LogFileFolder}
      - NereidLogFileFolder=${LogFileFolder}/NeriedLogs
      - KeystoneUrl=${KeystoneUrl}
      - KeystoneUserProfileUrl=${KeystoneUserProfileUrl}
      - KeystoneOpenIDUrl=${KeystoneOpenIDUrl}
      - KeystoneRegisterUrl=${KeystoneRegisterUrl}
      - KeystoneInviteUserUrl=${KeystoneInviteUserUrl}
      - KeystoneOpenIDClientId=${KeystoneOpenIDClientId}
      - KeystoneOpenIDClientSecret=${KeystoneOpenIDClientSecret}
      - DefaultModalDialogButtonCssClasses=${DefaultModalDialogButtonCssClasses}
      - ParcelMapServiceUrl=${ParcelMapServiceUrl}
      - MapServiceLayerNameParcel=${MapServiceLayerNameParcel}
      - MapServiceLayerNameLandUseBlock=${MapServiceLayerNameLandUseBlock}
      - MapServiceLayerNameRegionalSubbasin=${MapServiceLayerNameRegionalSubbasin}
      - AutoDelineateServiceUrl=${AutoDelineateServiceUrl}
      - HRUServiceBaseUrl=${HRUServiceBaseUrl}
      - RegionalSubbasinServiceUrl=${RegionalSubbasinServiceUrl}
      - ModelBasinServiceUrl=${ModelBasinServiceUrl}
      - PrecipitationZoneServiceUrl=${PrecipitationZoneServiceUrl}
      - OCTAPrioritizationServiceUrl=${OCTAPrioritizationServiceUrl}
      - NominatimAPIKey=${NominatimAPIKey}
      - PathToPyqgisTestScript=${PathToPyqgisTestScript}
      - PyqgisWorkingDirectory=${PyqgisWorkingDirectory}
      - PathToPyqgisLauncher=${PathToPyqgisLauncher}
      - PathToPyqgisProjData=${PathToPyqgisProjData}
      - PyqgisUsername=${PyqgisUsername}
      - PyqgisPassword=${PyqgisPassword}
      - NereidUrl=${NereidUrl}
      - PathToFieldVisitUploadTemplate=${PathToFieldVisitUploadTemplate}      