version: '3.4'

services:
  neptune.webmvc:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - SECRET_PATH=${SECRET_PATH}
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - SitkaEmailRedirect=${SitkaEmailRedirect}
      - SitkaSupportEmail=${SitkaSupportEmail}
      - DoNotReplyEmail=${DoNotReplyEmail}
      - MailLogBcc=${MailLogBcc}
      - KeystoneOpenIDUrl=${KeystoneOpenIDUrl}
      - KeystoneOpenIDClientID=${KeystoneOpenIDClientID}
      - MapServiceUrl=${MapServiceUrl}
      - AutoDelineateServiceUrl=${AutoDelineateServiceUrl}
      - HRUServiceBaseUrl=${HRUServiceBaseUrl}
      - GDALAPIBaseUrl=${GDALAPIBaseUrl}
      - OCGISBaseUrl=${OCGISBaseUrl}
      - PlanningModuleBaseUrl=${PlanningModuleBaseUrl}
      - DatabaseServerName=${DatabaseServerName}
      - DatabaseName=${DatabaseName}
      - PathToPyqgisTestScript=${PathToPyqgisTestScript}
      - PyqgisWorkingDirectory=${PyqgisWorkingDirectory}
      - PathToPyqgisLauncher=${PathToPyqgisLauncher}
      - PathToPyqgisProjData=${PathToPyqgisProjData}
      - PathToFieldVisitUploadTemplate=${PathToFieldVisitUploadTemplate}
      - RecaptchaPublicKey=${RecaptchaPublicKey}
      - RecaptchaPrivateKey=${RecaptchaPrivateKey}
      - RecaptchaValidatorUrl=${RecaptchaValidatorUrl}

  neptune.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - SECRET_PATH=${NeptuneAPISecretPath}
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - SitkaEmailRedirect=${SitkaEmailRedirect}
      - SitkaSupportEmail=${SitkaSupportEmail}
      - DoNotReplyEmail=${DoNotReplyEmail}
      - MailLogBcc=${MailLogBcc}
      - KeystoneOpenIDUrl=${KeystoneOpenIDUrl}
      - KeystoneRedirectUrl=${KeystoneRedirectUrl}
      - OcStormwaterToolsBaseUrl=${OcStormwaterToolsBaseUrl}
      - NereidUrl=${NereidUrl}
      - GDALAPIBaseUrl=${GDALAPIBaseUrl}
      - OCGISBaseUrl=${OCGISBaseUrl}
      - PlanningModuleBaseUrl=${PlanningModuleBaseUrl}
      - DatabaseServerName=${DatabaseServerName}
      - DatabaseName=${DatabaseName}
      - PathToPyqgisTestScript=${PathToPyqgisTestScript}
      - PyqgisWorkingDirectory=${PyqgisWorkingDirectory}
      - PathToPyqgisLauncher=${PathToPyqgisLauncher}
      - PathToPyqgisProjData=${PathToPyqgisProjData}

  neptune.gdalapi:
    environment:
      - AzureBlobStorageConnectionString=${AzureBlobStorageConnectionString}