version: '3.4'

services:
  neptune.webmvc:
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - SECRET_PATH=${SECRET_PATH}
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - SitkaEmailRedirect=${SitkaEmailRedirect}
      - SitkaSupportEmail=${SitkaSupportEmail}
      - DoNotReplyEmail=${DoNotReplyEmail}
      - MailLogBcc=${MailLogBcc}
      - RecaptchaPublicKey=${RecaptchaPublicKey}
      - RecaptchaPrivateKey=${RecaptchaPrivateKey}
      - RecaptchaValidatorUrl=${RecaptchaValidatorUrl}
      - Ogr2OgrExecutable=${Ogr2OgrExecutable}
      - OgrInfoExecutable=${OgrInfoExecutable}
      - LogFileFolder=${LogFileFolder}
      - KeystoneOpenIDUrl=${KeystoneOpenIDUrl}
      - KeystoneOpenIDClientID=${KeystoneOpenIDClientID}
      - ParcelMapServiceUrl=${ParcelMapServiceUrl}
      - MapServiceLayerNameParcel=${MapServiceLayerNameParcel}
      - MapServiceLayerNameLandUseBlock=${MapServiceLayerNameLandUseBlock}
      - MapServiceLayerNameRegionalSubbasin=${MapServiceLayerNameRegionalSubbasin}
      - AutoDelineateServiceUrl=${AutoDelineateServiceUrl}
      - HRUServiceBaseUrl=${HRUServiceBaseUrl}
      - RegionalSubbasinServiceUrl=${RegionalSubbasinServiceUrl}
      - ModelBasinServiceUrl=${ModelBasinServiceUrl}
      - PrecipitationZoneServiceUrl=${PrecipitationZoneServiceUrl}
      - OCTAPrioritizationServiceUrl=${OCTAPrioritizationServiceUrl}
      - PathToPyqgisTestScript=${PathToPyqgisTestScript}
      - PyqgisWorkingDirectory=${PyqgisWorkingDirectory}
      - PathToPyqgisLauncher=${PathToPyqgisLauncher}
      - PathToPyqgisProjData=${PathToPyqgisProjData}
      - PlanningModuleUrl=${PlanningModuleUrl}
      - PathToFieldVisitUploadTemplate=${PathToFieldVisitUploadTemplate}

  neptune.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - SECRET_PATH=${NeptuneAPISecretPath}
      - KeystoneOpenIDUrl=${KeystoneOpenIDUrl}
      - SitkaEmailRedirect=${SitkaEmailRedirect}
      - DoNotReplyEmail=${DoNotReplyEmail}
      - KeystoneRedirectUrl=${KeystoneRedirectUrl}
      - APPINSIGHTS_INSTRUMENTATIONKEY=${APPINSIGHTS_INSTRUMENTATIONKEY}
      - OcStormwaterToolsBaseUrl=${OcStormwaterToolsBaseUrl}
      - NereidUrl=${NereidUrl}
      - GDALAPIBaseUrl=${GDALAPIBaseUrl}

  neptune.gdalapi:
    environment:
      - AzureBlobStorageConnectionString=${AzureBlobStorageConnectionString}