services:
  neptune.webmvc:
    build:
      args:
        source: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - SECRET_PATH=${SECRET_PATH}
      - SitkaEmailRedirect=${SitkaEmailRedirect}
      - SitkaSupportEmail=${SitkaSupportEmail}
      - DoNotReplyEmail=${DoNotReplyEmail}
      - MailLogBcc=${MailLogBcc}
      - KeystoneOpenIDUrl=${KeystoneOpenIDUrl}
      - KeystoneOpenIDClientID=${KeystoneOpenIDClientID}
      - MapServiceUrl=${MapServiceUrl}
      - NereidUrl=${NereidUrl}
      - GDALAPIBaseUrl=${GDALAPIBaseUrl}
      - QGISAPIBaseUrl=${QGISAPIBaseUrl}
      - OCGISBaseUrl=${OCGISBaseUrl}
      - PlanningModuleBaseUrl=${PlanningModuleBaseUrl}
      - PathToFieldVisitUploadTemplate=${PathToFieldVisitUploadTemplate}
      - PathToOVTAUploadTemplate=${PathToOVTAUploadTemplate}
      - RecaptchaPublicKey=${RecaptchaPublicKey}
      - RecaptchaPrivateKey=${RecaptchaPrivateKey}
      - RecaptchaValidatorUrl=${RecaptchaValidatorUrl}
      - GoogleRecaptchaV3Config__SiteKey=${GoogleRecaptchaV3SiteKey}
      - GoogleRecaptchaV3Config__SecretKey=${GoogleRecaptchaV3SecretKey}
      - GoogleRecaptchaV3Config__VerifyUrl=${GoogleRecaptchaV3VerifyUrl}
      - AzureBlobStorageConnectionString=${AzureBlobStorageConnectionString}
    ports:
      - "6211:8080"
      - "6212:8081"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  neptune.api:
    build:
      args:
        source: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - SECRET_PATH=${NeptuneAPISecretPath}
      - SitkaEmailRedirect=${SitkaEmailRedirect}
      - SitkaSupportEmail=${SitkaSupportEmail}
      - DoNotReplyEmail=${DoNotReplyEmail}
      - MailLogBcc=${MailLogBcc}
      - KeystoneOpenIDUrl=${KeystoneOpenIDUrl}
      - KeystoneRedirectUrl=${KeystoneRedirectUrl}
      - OcStormwaterToolsBaseUrl=${OcStormwaterToolsBaseUrl}
      - NereidUrl=${NereidUrl}
      - GDALAPIBaseUrl=${GDALAPIBaseUrl}
      - QGISAPIBaseUrl=${QGISAPIBaseUrl}
      - OCGISBaseUrl=${OCGISBaseUrl}
      - PlanningModuleBaseUrl=${PlanningModuleBaseUrl}
      - AzureBlobStorageConnectionString=${AzureBlobStorageConnectionString}
    ports:
      - "8211:8080"
      - "8212:8081"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  neptune.gdalapi:
    build:
      args:
        source: .
    hostname: gdalapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - AzureBlobStorageConnectionString=${AzureBlobStorageConnectionString}
    ports:
      - "8231:8080"

  neptune.qgisapi:
    image: neptune/qgisapi
    build:
      context: ..
      dockerfile: Neptune.QGISAPI/Dockerfile
      args:
        source: .
    hostname: qgisapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - SECRET_PATH=${QGISAPISecretPath}
    ports:
      - "8232:8080"

  geoserver:
    container_name: neptune_geoserver
    image: kartoza/geoserver:2.25.2
    environment:
      - ENABLE_JSONP=true
      - CATALINA_OPTS=-DALLOW_ENV_PARAMETRIZATION=true
      - STABLE_EXTENSIONS=sqlserver-plugin
      - TOMCAT_EXTRAS=false
      - ROOT_WEBAPP_REDIRECT=true
      - SAMPLE_DATA=false
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=${GeoserverAdminPassword}
    ports:
      - 127.0.0.1:8780:8080
    volumes:
      - c:/git/sitkatech/neptune/Neptune.GeoServer/data_dir:/opt/geoserver/data_dir

  neptune.celeryworker:
    container_name: nereid_celeryworker
    image: containersesaqa.azurecr.io/neptune/celeryworker:v0.10.1
    environment:
      CELERY_BROKER_URL: redis://nereid_redis:6379/0
      CELERY_RESULT_BACKEND: redis://nereid_redis:6379/0
    volumes:
      - c:/Sitka/Neptune/nereid_data:/nereid/nereid/data/project_data
    ports:
      - "8233:5555"

  neptune.flower:
    container_name: nereid_flower
    image: containersesaqa.azurecr.io/neptune/flower:v0.10.1
    environment:
      CELERY_BROKER_URL: redis://nereid_redis:6379/0
      CELERY_RESULT_BACKEND: redis://nereid_redis:6379/0

  neptune.nereid:
    container_name: nereid
    image: containersesaqa.azurecr.io/neptune/nereid:v0.10.1
    hostname: nereid
    command: bash /start-reload.sh
    volumes:
      - c:/Sitka/Neptune/nereid_data:/nereid/nereid/data/project_data
    ports:
      - "8234:80"
    environment:
      CELERY_BROKER_URL: redis://nereid_redis:6379/0
      CELERY_RESULT_BACKEND: redis://nereid_redis:6379/0
      NEREID_ASYNC_MODE: replace

  neptune.nereid-tests:
    container_name: nereid_tests
    image: containersesaqa.azurecr.io/neptune/nereid-tests:v0.10.1
    environment:
      CELERY_BROKER_URL: redis://nereid_redis:6379/0
      CELERY_RESULT_BACKEND: redis://nereid_redis:6379/0
      NEREID_ASYNC_MODE: replace
    volumes:
      - c:/Sitka/Neptune/nereid_data:/nereid/nereid/data/project_data

  neptune.redis:
    container_name: nereid_redis
    image: containersesaqa.azurecr.io/neptune/redis:v0.10.1