{{ if eq .Values.global.env.name "qa" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webmvc.fullname" . }}-qa-configmap
data:
  SECRET_PATH: "/app/secrets/neptuneWebMvcSecrets"
  DOCKER_BUILD_SOURCE: "."
  ASPNETCORE_ENVIRONMENT: "Staging"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  APPINSIGHTS_INSTRUMENTATIONKEY: "{{ .Values.global.env.appInsightsInstrumentationKey }}"
  SitkaSupportEmail: "h2o.team@esassoc.com"
  SitkaEmailRedirect: "notifications-qa@sitkatech.com"
  DoNotReplyEmail: "donotreply@ocstormwatertools.org"
  ParcelMapServiceUrl: "https://{{ .Values.global.domains.geoserver }}/geoserver/OCStormwater/ows"
  MapServiceLayerNameParcel: "OCStormwater:Parcels"
  MapServiceLayerNameLandUseBlock: "OCStormwater:LandUseBlocks"
  MapServiceLayerNameRegionalSubbasin: "OCStormwater:RegionalSubbasins"
  AutoDelineateServiceUrl: "https://www.ocgis.com/arcpub/rest/services/Flood/GlobalStormwaterDelineation/GPServer/Global%20Stormwater%20Delineation/"
  HRUServiceBaseUrl: "https://www.ocgis.com/arcpub/rest/services/Environmental_Resources/HRUSummary/GPServer/HRUSummary"
  PlanningModuleBaseUrl: "https://{{ .Values.global.domains.web }}"
  GDALAPIBaseUrl: "http://{{ .Values.global.domains.gdalApi }}"
  OCGISBaseUrl: "https://ocgis.com/arcpub/rest/services/"
  PathToPyqgisTestScript: "PyQgis/TestPyqgisMssql.py"
  PyqgisWorkingDirectory: "PyQgis"
  PathToPyqgisLauncher: "/bin/python-qgis-ltr.bat"
  PathToPyqgisProjData: "/share/proj"
  PathToFieldVisitUploadTemplate: "Content/Bulk_Upload_FieldVisists_for_Trash_Screens_Template.xlsx"
  KeystoneOpenIDUrl: "https://identity-qa.sitkatech.com"
  KeystoneOpenIDClientID: "Neptune"
{{ end }}