apiVersion: v1
kind: Secret
metadata:
  name: neptune-webmvc-secrets
type: Opaque
stringData:
  neptuneWebMvcSecrets: |
    {
      "DatabaseConnectionString": "Data Source={{ .Values.global.env.dbServer }};Initial Catalog={{ .Values.global.env.databaseName }};Persist Security Info=True;User ID={{ .Values.global.env.sqlUsername }};Password={{ .Values.global.secrets.apiSqlPassword }}",
      "SendGridApiKey": "{{ .Values.global.secrets.sendGridApiKey }}",
      "AzureBlobStorageConnectionString": "DefaultEndpointsProtocol=https;AccountName={{ .Values.global.secrets.applicationStorageAccountName }};AccountKey={{ .Values.global.secrets.applicationStorageAccountKey }};EndpointSuffix=core.windows.net",
      "KeystoneOpenIDClientSecret": "{{ .Values.global.secrets.keystoneOpenIDClientSecret }}",
      "GoogleRecaptchaV3Config": {
        "SiteKey": "{{ .Values.global.secrets.recaptchaV3SiteKey }}",
        "SecretKey": "{{ .Values.global.secrets.recaptchaV3SecretKey }}",
        "VerifyUrl": "https://www.google.com/recaptcha/api/siteverify"
      }
    }