--select * from dbo.CustomAttributeValue
ALTER TABLE dbo.TreatmentBMPTypeCustomAttributeType DROP CONSTRAINT FK_TreatmentBMPTypeCustomAttributeType_CustomAttributeType_CustomAttributeTypeID
ALTER TABLE dbo.CustomAttribute DROP CONSTRAINT FK_CustomAttribute_TreatmentBMPTypeCustomAttributeType_TreatmentBMPTypeCustomAttributeTypeID
ALTER TABLE dbo.CustomAttribute DROP CONSTRAINT FK_CustomAttribute_TreatmentBMPTypeCustomAttributeType_TreatmentBMPTypeID_CustomAttributeTypeID

update dbo.TreatmentBMPTypeCustomAttributeType set CustomAttributeTypeID = 69 where CustomAttributeTypeID = 59
update dbo.CustomAttribute set CustomAttributeTypeID = 69 where CustomAttributeTypeID = 59

ALTER TABLE dbo.TreatmentBMPTypeCustomAttributeType  WITH CHECK ADD  CONSTRAINT FK_TreatmentBMPTypeCustomAttributeType_CustomAttributeType_CustomAttributeTypeID FOREIGN KEY(CustomAttributeTypeID)
REFERENCES dbo.CustomAttributeType (CustomAttributeTypeID)
GO

ALTER TABLE dbo.TreatmentBMPTypeCustomAttributeType CHECK CONSTRAINT FK_TreatmentBMPTypeCustomAttributeType_CustomAttributeType_CustomAttributeTypeID
GO

ALTER TABLE dbo.CustomAttribute  WITH CHECK ADD  CONSTRAINT FK_CustomAttribute_TreatmentBMPTypeCustomAttributeType_TreatmentBMPTypeCustomAttributeTypeID FOREIGN KEY(TreatmentBMPTypeCustomAttributeTypeID)
REFERENCES dbo.TreatmentBMPTypeCustomAttributeType (TreatmentBMPTypeCustomAttributeTypeID)
GO

ALTER TABLE dbo.CustomAttribute CHECK CONSTRAINT FK_CustomAttribute_TreatmentBMPTypeCustomAttributeType_TreatmentBMPTypeCustomAttributeTypeID
GO

ALTER TABLE dbo.CustomAttribute  WITH CHECK ADD  CONSTRAINT FK_CustomAttribute_TreatmentBMPTypeCustomAttributeType_TreatmentBMPTypeID_CustomAttributeTypeID FOREIGN KEY(TreatmentBMPTypeID, CustomAttributeTypeID)
REFERENCES dbo.TreatmentBMPTypeCustomAttributeType (TreatmentBMPTypeID, CustomAttributeTypeID)
GO

ALTER TABLE dbo.CustomAttribute CHECK CONSTRAINT FK_CustomAttribute_TreatmentBMPTypeCustomAttributeType_TreatmentBMPTypeID_CustomAttributeTypeID
GO

