CREATE TABLE [dbo].[ParcelGeometry](
	[ParcelGeometryID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_ParcelGeometry_ParcelGeometryID] PRIMARY KEY,
	[ParcelID] [int] NOT NULL CONSTRAINT [AK_ParcelGeometry_ParcelID] UNIQUE CONSTRAINT [FK_ParcelGeometry_Parcel_ParcelID] FOREIGN KEY REFERENCES [dbo].[Parcel] ([ParcelID]),
	[GeometryNative] [geometry] NOT NULL,
	[Geometry4326] [geometry] NULL
)
GO

CREATE SPATIAL INDEX [SPATIAL_ParcelGeometry_Geometry4326] ON [dbo].[ParcelGeometry]
(
	[Geometry4326]
)USING  GEOMETRY_AUTO_GRID 
WITH (BOUNDING_BOX =(-119, 33, -117, 34), 
CELLS_PER_OBJECT = 8, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

CREATE SPATIAL INDEX [SPATIAL_ParcelGeometry_GeometryNative] ON [dbo].[ParcelGeometry]
(
	[GeometryNative]
)USING  GEOMETRY_AUTO_GRID 
WITH (BOUNDING_BOX =(5993240, 2087140, 6207830, 2292500), 
CELLS_PER_OBJECT = 8, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)