CREATE TABLE [dbo].[TreatmentBMPModelingAttribute](
	[TreatmentBMPModelingAttributeID] [int] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_TreatmentBMPModelingAttribute_TreatmentBMPModelingAttributeID] PRIMARY KEY,
	[TreatmentBMPID] [int] NOT NULL CONSTRAINT [AK_TreatmentBMPModelingAttribute_TreatmentBMPID] UNIQUE CONSTRAINT [FK_TreatmentBMPModelingAttribute_TreatmentBMP_TreatmentBMPID] FOREIGN KEY REFERENCES [dbo].[TreatmentBMP] ([TreatmentBMPID]),
	[UpstreamTreatmentBMPID] [int] NULL CONSTRAINT [FK_TreatmentBMPModelingAttribute_TreatmentBMP_UpstreamTreatmentBMPID_TreatmentBMPID] FOREIGN KEY REFERENCES [dbo].[TreatmentBMP] ([TreatmentBMPID]),
	[AverageDivertedFlowrate] [float] NULL,
	[AverageTreatmentFlowrate] [float] NULL,
	[DesignDryWeatherTreatmentCapacity] [float] NULL,
	[DesignLowFlowDiversionCapacity] [float] NULL,
	[DesignMediaFiltrationRate] [float] NULL,
	[DiversionRate] [float] NULL,
	[DrawdownTimeforWQDetentionVolume] [float] NULL,
	[EffectiveFootprint] [float] NULL,
	[EffectiveRetentionDepth] [float] NULL,
	[InfiltrationDischargeRate] [float] NULL,
	[InfiltrationSurfaceArea] [float] NULL,
	[MediaBedFootprint] [float] NULL,
	[PermanentPoolorWetlandVolume] [float] NULL,
	[RoutingConfigurationID] [int] NULL CONSTRAINT [FK_TreatmentBMPModelingAttribute_RoutingConfiguration_RoutingConfigurationID] FOREIGN KEY REFERENCES [dbo].[RoutingConfiguration] ([RoutingConfigurationID]),
	[StorageVolumeBelowLowestOutletElevation] [float] NULL,
	[SummerHarvestedWaterDemand] [float] NULL,
	[TimeOfConcentrationID] [int] NULL CONSTRAINT [FK_TreatmentBMPModelingAttribute_TimeOfConcentration_TimeOfConcentrationID] FOREIGN KEY REFERENCES [dbo].[TimeOfConcentration] ([TimeOfConcentrationID]),
	[DrawdownTimeForDetentionVolume] [float] NULL,
	[TotalEffectiveBMPVolume] [float] NULL,
	[TotalEffectiveDrywellBMPVolume] [float] NULL,
	[TreatmentRate] [float] NULL,
	[UnderlyingHydrologicSoilGroupID] [int] NULL CONSTRAINT [FK_TreatmentBMPModelingAttribute_UnderlyingHydrologicSoilGroup_UnderlyingHydrologicSoilGroupID] FOREIGN KEY REFERENCES [dbo].[UnderlyingHydrologicSoilGroup] ([UnderlyingHydrologicSoilGroupID]),
	[UnderlyingInfiltrationRate] [float] NULL,
	[WaterQualityDetentionVolume] [float] NULL,
	[WettedFootprint] [float] NULL,
	[WinterHarvestedWaterDemand] [float] NULL,
	[MonthsOfOperationID] [int] NULL CONSTRAINT [FK_TreatmentBMPModelingAttribute_MonthsOfOperation_MonthsOfOperationID] FOREIGN KEY REFERENCES [dbo].[MonthsOfOperation] ([MonthsOfOperationID]),
	[DryWeatherFlowOverrideID] [int] NULL CONSTRAINT [FK_TreatmentBMPModelingAttribute_DryWeatherFlowOverride_DryWeatherFlowOverrideID] FOREIGN KEY REFERENCES [dbo].[DryWeatherFlowOverride] ([DryWeatherFlowOverrideID]),
)