CREATE TABLE [dbo].[gt_pk_metadata](
	[table_schema] [varchar](32),
	[table_name] [varchar](32),
	[pk_column] [varchar](32),
	[pk_column_idx] [int] NULL,
	[pk_policy] [varchar](32) NULL,
	[pk_sequence] [varchar](64) NULL,
	constraint AK_gt_pk_metadata_table_schema_table_name_pk_column UNIQUE 
	(
		[table_schema] ASC,
		[table_name] ASC,
		[pk_column] ASC
	),
	constraint CK_gt_pk_metadata_pk_policy CHECK  (([pk_policy]='autogenerated' OR [pk_policy]='assigned' OR [pk_policy]='sequence'))
)
