SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LSPCBasinStaging](
	[LSPCBasinStagingID] [int] IDENTITY(1,1) NOT NULL,
	[LSPCBasinKey] [int] NOT NULL,
	[LSPCBasinName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[LSPCBasinGeometry] [geometry] NOT NULL,
 CONSTRAINT [PK_LSPCBasinStaging_LSPCBasinStagingID] PRIMARY KEY CLUSTERED 
(
	[LSPCBasinStagingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_LSPCBasinStaging_LSPCBasinKey] UNIQUE NONCLUSTERED 
(
	[LSPCBasinKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
