SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OperationMonth](
	[OperationMonthID] [int] NOT NULL,
	[OperationMonthName] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[OperationMonthDisplayName] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[OperationMonthNereidAlias] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_OperationMonth_OperationMonthID] PRIMARY KEY CLUSTERED 
(
	[OperationMonthID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_OperationMonth_OperationMonthDisplayName] UNIQUE NONCLUSTERED 
(
	[OperationMonthDisplayName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_OperationMonth_OperationMonthName] UNIQUE NONCLUSTERED 
(
	[OperationMonthName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
