SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LEGAL_LOTS_ATTRIBUTES_4326](
	[OBJECTID] [int] NULL,
	[LEGAL_DESCR] [varchar](256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RECORDER_NO] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAIL_ADDRESS] [varchar](102) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZONECLASS] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DESCRIPTIO] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CATEGORY] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ZONE_AND_Housing] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Dist_Regs] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Link] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OWNER_NAMES] [varchar](96) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SITE_ADDRESS] [varchar](102) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COLOR] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ASSESSMENT_NO] [varchar](22) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SITE_ADDR_NO] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SITE_STREET_PREFIX] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SITE_STREET_NAME] [varchar](52) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SITE_STREET_SUFFIX] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SITE_CITY_STATE] [varchar](56) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SITE_ZIP5] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAIL_ADDR_NO] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAIL_PREFIX] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAIL_STREET] [varchar](52) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAIL_CITY_STATE] [varchar](56) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAIL_UNIT_NO] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAIL_SUFFIX] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MAIL_ZIP5] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOT_SIZE] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DOC_REF_NO] [varchar](14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DOC_REF_DATE] [varchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FabricOID] [int] NULL,
	[USE_DQ_LANDUSE] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModifyDate] [datetime2](7) NULL,
	[SQFT_HOME] [int] NULL,
	[SQFT_LOT] [int] NULL,
	[SALE_AMT] [float] NULL,
	[SALE_TYPE] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DOC_SELLER_NAME] [varchar](52) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DOC_BUYER_NAME] [varchar](52) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DOC_DEED_TYPE] [varchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SALE_RECORD_DATE] [datetime2](7) NULL,
	[ASSD_AMT] [float] NULL,
	[LAND_VAL] [float] NULL,
	[BLDG_VAL] [float] NULL,
	[SHAPE_Length] [float] NULL,
	[SHAPE_Area] [float] NULL,
	[GEOM] [geometry] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
