SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FieldVisitType](
	[FieldVisitTypeID] [int] NOT NULL,
	[FieldVisitTypeName] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FieldVisitTypeDisplayName] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_FieldVisitType_FieldVisitTypeID] PRIMARY KEY CLUSTERED 
(
	[FieldVisitTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_FieldVisitType_FieldVisitTypeName] UNIQUE NONCLUSTERED 
(
	[FieldVisitTypeName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
