SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ModelBasin](
	[ModelBasinID] [int] IDENTITY(1,1) NOT NULL,
	[ModelBasinKey] [int] NOT NULL,
	[ModelBasinGeometry] [geometry] NOT NULL,
	[LastUpdate] [datetime] NOT NULL,
	[ModelBasinState] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ModelBasinRegion] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_ModelBasin_ModelBasinID] PRIMARY KEY CLUSTERED 
(
	[ModelBasinID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_ModelBasin_ModelBasinKey] UNIQUE NONCLUSTERED 
(
	[ModelBasinKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
