SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NeptuneArea](
	[NeptuneAreaID] [int] NOT NULL,
	[NeptuneAreaName] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[NeptuneAreaDisplayName] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SortOrder] [int] NOT NULL,
	[ShowOnPrimaryNavigation] [bit] NOT NULL,
 CONSTRAINT [PK_NeptuneArea_NeptuneAreaID] PRIMARY KEY CLUSTERED 
(
	[NeptuneAreaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_NeptuneArea_NeptuneAreaDisplayName] UNIQUE NONCLUSTERED 
(
	[NeptuneAreaDisplayName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_NeptuneArea_NeptuneAreaName] UNIQUE NONCLUSTERED 
(
	[NeptuneAreaName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
