SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LSPCBasin](
	[LSPCBasinID] [int] IDENTITY(1,1) NOT NULL,
	[LSPCBasinKey] [int] NOT NULL,
	[LSPCBasinName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[LSPCBasinGeometry] [geometry] NOT NULL,
	[LastUpdate] [datetime] NOT NULL,
 CONSTRAINT [PK_LSPCBasin_LSPCBasinID] PRIMARY KEY CLUSTERED 
(
	[LSPCBasinID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_LSPCBasin_LSPCBasinKey] UNIQUE NONCLUSTERED 
(
	[LSPCBasinKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
